Added new script 'dev' to start the app using single command
Marlon-Monroy/gotron-react-boilerplate pull request #2
Opened 2020-10-09 14:04 UTC by DTan13

2020-10-09 16:46 UTC, ms-monroy requested changes

2020-10-09 16:46 UTC, ms-monroy commented on README.md
>  ```
lets annotate the snippet as `bash` code

2020-10-09 20:23 UTC, DTan13 commented on README.md
>  ```
I will do the same for all snippets in README

2020-10-10 16:31 UTC, DTan13 commented on README.md
>  ```
@ms-monroy Do I need to change something else?

2020-10-10 17:25 UTC, merged